# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'macOS-latest'

variables:
  LT_USERNAME: 'Your_LambdaTest_Username'
  LT_ACCESS_KEY: 'Your_LambdaTest_Access_Key'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g protractor
    cd conf
    protractor parallel.conf.js  //for executing parallel testing
  displayName: 'npm install and build'